### PR TITLE
TotalSent-Total Bounce is replaced by TotalDelivered and constant table is added in base view

### PR DESCRIPTION
**Pull request by Krsrinidhi**
…elivered and updated the constant table in base view

### CODE REVIEW

**Review by tarasovv1 — COMMENTED** [review]
Please, be consistent in "description" field: 
1. Add or remove dots at the end in all the descriptions.
2. Remove white space at the end of "Total count of Emails BOUNCED per job id " desc.
3. "Emails" word should start from Uppercase in all the descriptions.
4. "The total number of emails click as per job id by recipient." should be "The total number of Emails clicks as per job id by recipient."
5. "The percentage of bounce email." should be "The percentage of bounce Emails."
6. Description in sum_of_sent_email is not correct, should be "Total count of Emails SENT per job id."
7. "Total emails unsubscribed." does not sound very good. Could we have it as "Total visitors unsubscribed." ?

**Review by tarasovv1 — APPROVED** [review]
All good from my side. @pthoutam-googler @thjennifer Please, proceed with your review.

**Review by pthoutam-googler — APPROVED** [review]
LGTM

**Review by tarasovv1 — COMMENTED** [review]
Could you please revert the description in  "sum_of_unsubscribe" measure back to "Total emails unsubscribed." as was discussed with DAs and BA. Thanks!

**Review by tarasovv1 — APPROVED** [review]

**Review by tarasovv1 — APPROVED** [review]

**Review by thjennifer — APPROVED** [review]
LGTM

**Comment by TatsianaBab** [comment]
Empty lines (105, 107) at the end of the job_agg_rfn.view look incorrect.

**Comment by TatsianaBab** [comment]
Empty lines (105, 107) at the end of the job_agg_rfn.view
look incorrect.

**Pull request merged**
